language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t venkatitsme6/complex -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true venkatitsme6/complex npm run test -- --coverage
  
after_success:
  - docker build -t venkatitsme6/multi-client ./client
  - docker build -t venkatitsme6/multi-server ./server
  - docker build -t venkatitsme6/multi-worker ./worker
  - docker build -t venkatitsme6/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push venkatitsme6/multi-client
  - docker push venkatitsme6/multi-server
  - docker push venkatitsme6/multi-worker
  - docker push venkatitsme6/multi-nginx
  
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker-1
  env: Multidocker1-env
  bucket_name: elasticbeanstalk-us-east-2-941396074535
  bucket_path: multi-docker-1
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
